local_costmap:
global_frame: odom #map #odom #The "global_frame" parameter defines what coordinate frame the costmap should run in. it should be odom, but i don't know how to solve the errors
robot_base_frame: base_footprint #The "robot_base_frame" parameter defines the coordinate frame the costmap should reference for the base of the robot.
update_frequency: 10.0
publish_frequency: 10.0 #The "publish_frequency" parameter determines the rate, in Hz, at which the costmap will publish visualization information
rolling_window: true    #Setting the "rolling_window" parameter to true means that the costmap will remain centered around the robot as the robot moves through the world.

#The "width," "height," and "resolution" parameters set the width (meters), height (meters), and resolution (meters/cell) of the costmap. Note that its fine for the resolution of this grid to be different than the resolution of your static map, but most of the time we tend to set them equally. 
width: 0.8
height: 0.8
resolution: 0.01
transform_tolerance: 1.5