min_particles: 100
max_particles: 500
kld_err: 0.02
kld_z: 0.99
update_min_d: 0.2
update_min_a: 0.2
resample_interval: 1
transform_tolerance: 0.5
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0
# initial_pose_x: # defined in launch
# initial_pose_y: # defined in launch
initial_pose_a: 0.0
initial_cov_xx: 0.25
initial_cov_yy: 0.25
initial_cov_aa: 0.06854
gui_publish_rate: 50.0
save_pose_rate: 0.5
use_map_topic: false
first_map_only: true
selective_resampling: true

laser_min_range: -1.0
laser_max_range: -1.0
laser_max_beams: 180
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field

odom_model_type: diff
odom_alpha1: 0.1
odom_alpha2: 0.1
odom_alpha3: 0.1
odom_alpha4: 0.1
odom_alpha5: 0.1
odom_frame_id: odom
base_frame_id: base_link
global_frame_id: map
tf_broadcast: true